# Generated by Django 3.2 on 2023-11-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20231115_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlemodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
