# Generated by Django 3.2 on 2023-11-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_titlemodel_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='GenreModel',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='TitleModel',
            new_name='Title',
        ),
    ]
